### ISSUE TITLE
FX opens FX Text Edit instead of the file manager itself

### ISSUE THREAD

**Issue by ghost** [tanujnotes/Olauncher#122] opened 2021-09-11 03:46 UTC
I was trying to open FX file explorer but whenever i try opening FX it just redirects to FX Text Edit

https://user-images.githubusercontent.com/65075766/132935333-a0472071-d4a2-403f-ba7b-8a852dc70beb.mp4

I even properly tap the "FX" title but both of them just opens the Text Edit app

my workaround is use activity launcher but it would be pain in the ass to do it

**Comment by tanujnotes** [comment] 2021-09-13 16:35
This is a known issue. Olauncher currently does not support multiple icons/launch screen from the same app.

**Comment by yephny** [comment] 2021-11-07 11:57
Yeah, I'm having the same issue with SimpleReminder [as I noted here](https://github.com/felixwiemuth/SimpleReminder/issues/22), where the developer of the app explains it in detail.

**Comment by yephny** [comment] 2021-11-09 20:38
Duplicate of #79.

**Comment by yephny** [comment] 2022-08-22 14:54
This issue has been solved in v.3.5.4.

**Closed** 2022-08-22 14:55 UTC
Labels: bug
