### ISSUE TITLE
Smaller spacing date/clock applist on 3.4.(1)? 

### ISSUE THREAD

**Issue by ANDREW007CZ** [tanujnotes/Olauncher#123] opened 2021-09-12 21:46 UTC
With new version I have a lot of miss-taps to get calendar open. There is really small space between the elements. Clock could be higher, now they is a redundant space above them, squishing everything down. Screenshot from my 4"6' xperia x compact. 
Hard to get calendar opened... 

![Screenshot_20210912-234027](https://user-images.githubusercontent.com/26521196/133003743-278ddbca-5381-4a1c-8f54-a73a0229375b.png)

**Comment by JacksonCampbell99** [comment] 2021-09-22 04:45
Looks like your system scaling or font size is high and maybe like the app is playing in with extra unnecessary spacing as well.

**Comment by tanujnotes** [comment] 2021-09-28 17:28
Can you check the latest version `v3.4.2` and confirm if the issue is fixed?

**Comment by ANDREW007CZ** [comment] 2021-10-02 18:15
I think it is barely better. All I notice is that date is not bold now. But it is still hard to hit the right spot.

**Comment by ANDREW007CZ** [comment] 2021-10-02 18:16
![Screenshot_20210929-233527](https://user-images.githubusercontent.com/26521196/135727648-80b35b4d-7248-4f23-aba6-fee6d0782622.png)

**Comment by tanujnotes** [comment] 2021-10-02 18:21
My bad. I did make some changes but looks like it didn't work. I assure you it will be fixed in the next update. Meanwhile you can try having one less app on the home screen, if that works for you.

**Comment by ANDREW007CZ** [comment] 2021-10-02 18:24
Great, thanks a lot!

**Comment by tanujnotes** [comment] 2022-01-12 09:17
Is this resolved in the latest release? Can you please post a screenshot of the latest version?

**Comment by ANDREW007CZ** [comment] 2022-01-12 09:25
Yes, I believe font is smaller and all fits better. :) Thank you
![Screenshot_20220112-102135](https://user-images.githubusercontent.com/26521196/149102430-bccf10d1-7eab-4a8f-9ea4-0a0a59dd6e35.png)
.

**Comment by tanujnotes** [comment] 2022-01-12 09:27
Looks ok. Will try to make this even better in next release. Closing this for now.

**Closed by tanujnotes** 2022-01-12 09:27 UTC
