### ISSUE TITLE
[Bug] Apps get hidden in the swipe-up list

### ISSUE THREAD

**Issue by teemue** [tanujnotes/Olauncher#16] opened 2020-08-20 11:34 UTC
I've faced this issue three times so far: the app list, which contains all apps, hides roughly half of the installed apps. I have no idea how this happens or how to reproduce this. I haven't figured the pattern for which apps are hid: it's not alphabetical because I see apps from A to Z but many between aren't in the list.

If i go to settings, force quit and relaunch Olauncher, everything's normal again.

**Comment by tanujnotes** [comment] 2020-08-20 11:43
I need more information. Are you using the latest version (0.5)? Earlier versions had this issue but hopefully it's fixed in the latest one. I'll also need the Android version of your device. If possible, I need to know at least one app that goes missing from the list that I can install from the Play Store. Thank you.

**Comment by teemue** [comment] 2020-08-20 12:16
I built it myself just  before you released the newest APK but It should be the same source. However, I'll install prebuilt 0.5 and see if it occurs again.

**Comment by tanujnotes** [comment] 2020-08-24 13:54
Sorry that you guys are facing this issue. One possible cause for this might be that some invisible character is there on the search which is giving you a filtered app list. Seems unlikely but this is the only theory I have for now. I'll keep looking into this.

**Comment by Laesp** [comment] 2020-08-29 03:53
@tanujnotes Would be unlikely since the search resets every time you open and close the bar. I haven't seen the bug on the latest play store version as of yet, but I shall keep you updated and see if I can get a logcat if I reproduce.

**Comment by teemue** [comment] 2020-09-01 19:12
Haven't faced this problem for a while.
Thanks for 1.0 btw!

**Comment by tanujnotes** [comment] 2020-09-01 20:02
Thanks mate. Closing this issue then.

**Closed** 2020-09-01 20:02 UTC
Labels: bug
